### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 

### ISSUE THREAD

**Issue by Abbsalehi** [keunsoo-ko/CMT#1]
Dear authors, I have GPU, and torch.cuda.is_available() is True, and I am still getting the error. 
```
Load checkpoint from: ./checkpoint/Place2.pth
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    proposed = load_checkpoint(args.ckpt, proposed)
  File "/home/ab/PycharmProjects/CMT/utils.py", line 10, in load_checkpoint
    checkpoint = _load(path)
  File "/home/ab/PycharmProjects/CMT/utils.py", line 5, in _load
    checkpoint = torch.load(checkpoint_path)
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ab/anaconda3/envs/CMT/lib/python3.7/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by Fluffy-Shark-Workshop** [comment]
Hi, I also had the same problem, but it can be fixed by erasing the code 'os.environ["CUDA_VISIBLE_DEVICES"]="2"' on second line in demo.py. This line makes the PC use the specific GPU that you assigned.
